
	********************************************
	********************************************
	*** 1. SBI/NACE 1 digit (bedrijfstakken) ***
	********************************************
	********************************************

#delimit ;
	label def sbi20081D_full
	
	1 	"Landbouw, bosbouw en visserij"
	2	"Winning van delfstoffen"
	3	"Industrie"
	4	"Productie en distributie van en handel in elektriciteit, aardgas, stoom en gekoelde lucht" 	
	5	"Winning en distributie van water; afval- en afvalwaterbeheer en sanering" 
	6	"Bouwnijverheid"
	7	"Groot- en detailhandel; reparatie van auto's"
	8	"Vervoer en opslag"
	9 	"Logies-, maaltijd- en drankverstrekking"
	10 	"Informatie en communicatie"
	11	"Financiële instellingen"
	12 	"Verhuur van en handel in onroerend goed"
	13 	"Advisering, onderzoek en overige specialistische zakelijke dienstverlening"
	14	"Verhuur van roerende goederen en overige zakelijke dienstverlening"
	15	"Openbaar bestuur, overheidsdiensten en verplichte sociale verzekeringen"
	16	"Onderwijs"
	17	"Gezondheids- en welzijnszorg"
	18	"Cultuur, sport en recreatie"
	19	"Overige dienstverlening"
	20	"Huishoudens als werkgever"
	21	"Extraterritoriale organisaties en lichamen"
	;
#delimit cr

*** SHORT VERSION

#delimit ;
	label def sbi20081D_short
	
	1 	"A Agrarisch"
	2	"B Delfstoffen"
	3	"C Industrie"
	4	"D Energie" 	
	5	"E Water & Afval" 
	6	"F Bouw"
	7	"G Handel"
	8	"H Logistiek"
	9 	"I Horeca"
	10 	"J Media & IT"
	11	"K Financieel"
	12 	"L Onroerend"
	13 	"M Zakelijk"
	14	"N Facilitair"
	15	"O Overheid"
	16	"P Onderwijs"
	17	"Q Zorg & Welzijn"
	18	"R Cultuur & Recreatie"
	19	"S Overig"
	20	"T Huishoudens"
	21	"U Extraterritoriaal"
	;
#delimit cr


	**************************************
	**************************************
	*** 2. SBI/NACE 2 digit (sectoren) ***
	**************************************
	**************************************

#delimit ;
	label def sbi20082D_full
	1		"Landbouw, jacht en dienstverlening voor de landbouw en jacht"
	2		"Bosbouw, exploitatie van bossen en dienstverlening voor de bosbouw"
	3		"Visserij en kweken van vis en schaaldieren"
	6		"Winning van aardolie en aardgas"
	8		"Winning van delfstoffen (geen olie en gas)"
	9		"Dienstverlening voor de winning van delfstoffen"
	10		"Vervaardiging van voedingsmiddelen"
	11		"Vervaardiging van dranken"
	12		"Vervaardiging van tabaksproducten"
	13		"Vervaardiging van textiel"
	14		"Vervaardiging van kleding"
	15		"Vervaardiging van leer, lederwaren en schoenen"
	16		"Primaire houtbewerking en vervaardiging van artikelen van hout, kurk, riet en vlechtwerk ( geen meubels)"
	17		"Vervaardiging van papier, karton en papier- en kartonwaren"
	18		"Drukkerijen, reproductie van opgenomen media"
	19		"Vervaardiging van cokesovenproducten en aardolieverwerking"
	20		"Vervaardiging van chemische producten"
	21		"Vervaardiging van farmaceutische grondstoffen en producten"
	22		"Vervaardiging van producten van rubber en kunststof"
	23		"Vervaardiging van overige niet-metaalhoudende minerale producten"
	24		"Vervaardiging van metalen in primaire vorm"
	25		"Vervaardiging van producten van metaal (geen machines en apparaten)"
	26		"Vervaardiging van computers en van elektronische en optische apparatuur"
	27		"Vervaardiging van elektrische apparatuur"
	28		"Vervaardiging van overige machines en apparaten"
	29		"Vervaardiging van auto's, aanhangwagens en opleggers"
	30		"Vervaardiging van overige transportmiddelen"
	31		"Vervaardiging van meubels"
	32		"Vervaardiging van overige goederen"
	33		"Reparatie en installatie van machines en apparaten"
	35		"Productie en distributie van en handel in elektriciteit, aardgas, stoom en gekoelde lucht"
	36		"Winning en distributie van water"
	37		"Afvalwaterinzameling en -behandeling"
	38		"Afvalinzameling en -behandeling; voorbereiding tot recycling"
	39		"Sanering en overig afvalbeheer"
	41		"Algemene burgerlijke en utiliteitsbouw en projectontwikkeling"
	42		"Grond-, water- en wegenbouw (geen grondverzet)"
	43		"Gespecialiseerde werkzaamheden in de bouw"
	45		"Handel in en reparatie van auto’s, motorfietsen en aanhangers"
	46		"Groothandel en handelsbemiddeling (niet in auto's en motorfietsen)"
	47		"Detailhandel (niet in auto's)"
	49		"Vervoer over land"
	50		"Vervoer over water"
	51		"Luchtvaart"
	52		"Opslag en dienstverlening voor vervoer"
	53		"Post en koeriers"
	55		"Logiesverstrekking"
	56		"Eet- en drinkgelegenheden"
	58		"Uitgeverijen"
	59		"Productie en distributie van films en televisieprogramma´s; maken en uitgeven van geluidsopnamen"
	60		"Verzorgen en uitzenden van radio- en televisieprogramma's"
	61		"Telecommunicatie"
	62		"Dienstverlenende activiteiten op het gebied van informatietechnologie"
	63		"Dienstverlenende activiteiten op het gebied van informatie"
	64		"Financiële instellingen (geen verzekeringen en pensioenfondsen)"
	65		"Verzekeringen en pensioenfondsen (geen verplichte sociale verzekeringen)"
	66		"Overige financiële dienstverlening"
	68		"Verhuur van en handel in onroerend goed"
	69		"Rechtskundige dienstverlening, accountancy, belastingadvisering en administratie"
	70		"Holdings (geen financiële), concerndiensten binnen eigen concern en managementadvisering"
	71		"Architecten, ingenieurs en technisch ontwerp en advies; keuring en controle"
	72		"Speur- en ontwikkelingswerk"
	73		"Reclame en marktonderzoek"
	74		"Industrieel ontwerp en vormgeving, fotografie, vertaling en overige consultancy"
	75		"Veterinaire dienstverlening"
	77		"Verhuur en lease van auto's, consumentenartikelen, machines en overige roerende goederen"
	78		"Arbeidsbemiddeling, uitzendbureaus en personeelsbeheer"
	79		"Reisbemiddeling, reisorganisatie, toeristische informatie en reserveringsbureaus"
	80		"Beveiliging en opsporing"
	81		"Facility management, reiniging en landschapsverzorging"
	82		"Overige zakelijke dienstverlening"
	84		"Openbaar bestuur, overheidsdiensten en verplichte sociale verzekeringen"
	85		"Onderwijs"
	86		"Gezondheidszorg"
	87		"Verpleging, verzorging en begeleiding met overnachting"
	88		"Maatschappelijke dienstverlening zonder overnachting"
	90		"Kunst"
	91		"Culturele uitleencentra, openbare archieven, musea, dieren- en plantentuinen, natuurbehoud"
	92		"Loterijen en kansspelen"
	93		"Sport en recreatie"
	94		"Levensbeschouwelijke en politieke organisaties, belangen- en ideële organisaties, hobbyclubs"
	95		"Reparatie van computers en consumentenartikelen"
	96		"Wellness en overige dienstverlening; uitvaartbranche"
	97		"Huishoudens als werkgever van huishoudelijk personeel"
	98		"Niet-gespecificeerde productie van goederen en diensten door particuliere huishoudens voor eigen gebruik"
	99		"Extraterritoriale organisaties en lichamen"
	;
#delimit cr

*** SHORT VERSION	

#delimit ;
	label def sbi20082D_short
	1		"Landbouw"
	2		"Bosbouw"
	3		"Visserij"
	6		"Winning aardolie en gas"
	8		"Winning overige delfstoffen"
	9		"Dienstverlening winning"
	10		"Voedingsmiddelen"
	11		"Dranken"
	12		"Tabak"
	13		"Textiel"
	14		"Kleding"
	15		"Lederwaren en schoenen"
	16		"Houtbewerking(geen meubels)"
	17		"Papier en karton"
	18		"Reproductie media"
	19		"Cokes- en aardolieverwerking"
	20		"Chemisch"
	21		"Farmaceutisch"
	22		"Rubber en kunststof"
	23		"Oerige niet-metaal"
	24		"Metaal"
	25		"Metaalproducten"
	26		"Computers en optisch"
	27		"Elektrische apparatuur"
	28		"Overige machines"
	29		"Auto"
	30		"Overige transportmiddelen"
	31		"Meubels"
	32		"Overige industrie"
	33		"Reparatie machines"
	35		"Energie"
	36		"Water"
	37		"Afvalwaterinzameling"
	38		"Afvalinzameling"
	39		"Overig afval"
	41		"Utiliteitsbouw"
	42		"Grond-, water- en wegenbouw"
	43		"Gespecialiseerde bouw"
	45		"Auto (ook reparatie)"
	46		"Groothandel"
	47		"Detailhandel"
	49		"Vervoer over land"
	50		"Vervoer over water"
	51		"Luchtvaart"
	52		"Opslag"
	53		"(Post)koeriers"
	55		"Logies"
	56		"Restaurants"
	58		"Uitgeverijen"
	59		"Productie media"
	60		"Broadcasting"
	61		"Telecommunicatie"
	62		"Dienstverlening IT"
	63		"Dienstverlenende informatie"
	64		"Bankwezen"
	65		"Verzekering en pensioen"
	66		"Overige financieel"
	68		"Onroerend goed"
	69		"Advocatuur en accountants"
	70		"Holdings"
	71		"Architecten en ingenieurs"
	72		"Speur- en ontwikkelingswerk"
	73		"Marktonderzoek"
	74		"Vormgeving"
	75		"Veterinair"
	77		"Leasing"
	78		"Arbeidsbemiddeling"
	79		"Reisbemiddeling"
	80		"Beveiliging en opsporing"
	81		"Facilitair"
	82		"Overige zakelijk"
	84		"Overheid"
	85		"Onderwijs"
	86		"Gezondheidszorg"
	87		"Verzorging"
	88		"Welzijn"
	90		"Kunst"
	91		"Cultureel"
	92		"Loterijen en kansspelen"
	93		"Sport en recreatie"
	94		"Levensbeschouwelijk"
	95		"Reparatie consumenten"
	96		"Overig overig"
	97		"Huishoud(st)ers"
	98		"Huishoudende productie"
	99		"Extraterritoriaal"
	;
#delimit cr
